#!/bin/bash
OUT="conditionMap.txt"

FILE="models.txt"
row=1
while read line; do
	model="${line#*= }"
	if [ "$model" != "[](0x0)" ]; then
		echo $'\t'"elif row_label == \"$model\":" >> $OUT
		echo $'\t\t'"return $row" >> $OUT
		row=$((row+1))
	fi
done < $FILE

echo $'\t'"else:" >> $OUT
echo $'\t\t'"return 0" >> $OUT
